version: '3'
services:
  app:
    build:
      context: .
    image: f1712200682/webapp_app:latest
    env_file:
      - ./.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - webapp-data:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
  db:
    build:
      context: ./containers/mysql
    image: f1712200682/mysql:8.0
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: rootpass
  web:
    build:
      context: ./containers/nginx
    image: f1712200682/webapp_web:latest
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  webapp-data:
  public-data:
  tmp-data:
  log-data: