version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - webapp-data:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  webapp-data:
  public-data:
  tmp-data:
  log-data:

